### ISSUE TITLE
Client-side error for certain Indexers during lookup

### ISSUE THREAD

**Issue by davidd8** [willscott/cid.contact#25]
Looking up the example CID for the following Indexers: Leeway Hertz, results in a client side error (picture below). The error page also does not support the back button, breaking navigation, forcing a refresh to get back to the original page.

<img width="1791" alt="Screen Shot 2022-10-18 at 1 34 00 PM" src="https://user-images.githubusercontent.com/390075/196547036-899c8b1a-291a-40e0-b97d-7022a9e31f6e.png">

**Comment by willscott** [comment]
should be fixed by https://github.com/willscott/cid.contact/pull/26

that's available now on dev.cid.contact - confirming it fixes before promoting to prod

**Comment by davidd8** [comment]
I'm still seeing the error on dev.cid.contact

**Comment by willscott** [comment]
Do you have a specific CID you are testing that is causing the issue, or
is it any CID with leeway hertz?

--Will

**Comment by davidd8** [comment]
I've tested `bafybeigvgzoolc3drupxhlevdp2ugqcrbcsqfmcek2zxiw5wctk3xjpjwy` and `bafybeie7ubmpd4cdldmgoj7an5xnethutjvowsgbqbnevljn6icuxwo5ci`. Leeway Hertz seems to be the culprit, as it returns a `500` for both CIDs and other Indexers return `404`s. It seems the error handling on cid.contact needs to be able to handle 500s
