### ISSUE TITLE
Payload CID lookups are running into parsing syntax errors on home page.

### ISSUE THREAD

**Issue by davidd8** [willscott/cid.contact#3]
A cid lookup for bafybeibhc3giz64wmwctoswot7bydrn6ghu6cvt4kmrbyrtbvpesndskni at https://cid.contact/cid/bafybeibhc3giz64wmwctoswot7bydrn6ghu6cvt4kmrbyrtbvpesndskni results in a "no results for query" but breaks on the GUI: 
<img width="811" alt="Screen Shot 2022-03-16 at 4 12 33 PM" src="https://user-images.githubusercontent.com/390075/158707298-83977da1-fa87-4829-be45-2b05d48d1e73.png">

Expected: No results in the UI
Actual: Parse Error in the UI.

**Comment by willscott** [comment]
closing as deprecated
